config/routes.rb
Rails.application.routes.draw do
  resources :message_threads do
    resources :messages
  end
  root 'message_threads#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :message_thread
  belongs_to :user

  validates_presence_of :body, :message_thread_id, :user_id
end

app/models/message_thread.rb
class MessageThread < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(message_threads.sender_id = ? AND message_threads.recipient_id =?) OR (message_threads.sender_id = ? AND message_threads.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :message_threads, :foreign_key => :sender_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/message_threads_controller.rb
class MessageThreadsController < ApplicationController
	def index
		@users = User.all
		@message_threads = MessageThread.all
	end

	def create
   if MessageThread.between(params[:sender_id],params[:recipient_id]).present?
      @message_thread = MessageThread.between(params[:sender_id], params[:recipient_id]).first
    else
      @message_thread = MessageThread.create!(message_thread_params)
    end
    redirect_to message_thread_messages_path(@message_thread)
	end

private
	def message_thread_params
		params.permit(:sender_id, :recipient_id)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message_thread

  def index
    @messages = @message_thread.messages
    @message = @message_thread.messages.new
  end

  def new
    @message = @message_thread.messages.new
  end

  def create
    @message = @message_thread.messages.new(message_params)
    if @message.save
      redirect_to message_thread_messages_path(@message_thread)
    end
  end

private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end

  def set_message_thread
  	@message_thread = MessageThread.find(params[:message_thread_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_threads_helper.rb
module MessageThreadsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/message_threads/index.html.erb
<% current_user = User.first %>

<h3>Mailbox</h3>

<ul>
  <div class="item">
    <% @message_threads.each do |message_thread| %>
      <% if message_thread.sender_id == current_user.id || message_thread.recipient_id == current_user.id %>
        <% if message_thread.sender_id == current_user.id %>
          <% recipient = User.find(message_thread.recipient_id) %>
        <% else %>
          <% recipient = User.find(message_thread.sender_id) %>
        <% end %>
        <li><%= link_to recipient.first_name, message_thread_messages_path(message_thread)%></li>
      <% end %>
    <% end %>
  </div>
</ul>


<h3>All Users</h3>
<div>
  <% @users.each do |user| %>
    <% if user.id != current_user.id %>
    <div class="item">
      <%= user.first_name %> <%= link_to 'Message me!', message_threads_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
    </div>
    <% end %>
  <% end %>
</div>

app/views/messages/index.html.erb
<% current_user = User.first %>
<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header"><strong><%= user.first_name %></strong> <%= message.created_at %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
              <%= message.body %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@message_thread, @message], html: {class: "ui reply form"} do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>

<% end %>